### ISSUE TITLE
exporting failed

### ISSUE THREAD

**Issue by ro-hit81** [ucalyptus/EarthEngine-Deep-Learning#2]
I am trying to use deep learning for classifying image from sentinel2 satellite. While exporting table to cloud storage, I am getting error as : <Task EXPORT_FEATURES: Testing Export (FAILED)>, <Task EXPORT_FEATURES: Training Export (FAILED)>, <Task EXPORT_FEATURES: Testing Export (FAILED)>, <Task EXPORT_FEATURES: Training Export (FAILED)>, <Task EXPORT_IMAGE: Image Export (COMPLETED)>, <Task EXPORT_FEATURES: Testing Export (FAILED)>.....
<img width="939" alt="Untitled" src="https://user-images.githubusercontent.com/50332813/71771106-9324fb00-2f68-11ea-8af0-3a39bcdb7e09.png">

**Comment by ucalyptus** [comment]
Did you create a GCS bucket before this?

**Comment by ro-hit81** [comment]
No

**Comment by ro-hit81** [comment]
yeah i created the bucket.

**Comment by ucalyptus** [comment]
Did you create a user in GEE console?

**Comment by ro-hit81** [comment]
yes.
![image](https://user-images.githubusercontent.com/50332813/71831380-5e858080-30db-11ea-9127-14c50b0abb97.png)
I think this is what you meant.

**Comment by ucalyptus** [comment]
So you have an account

**Comment by ro-hit81** [comment]
Yes i have.. It's enough right? Having an account

**Comment by ro-hit81** [comment]
i will send you the code. will you check it

**Comment by ucalyptus** [comment]
@ro-hit81 yes pls share

**Comment by ro-hit81** [comment]
i have solved previous problem... but can you help me.. i want to have 5
features in my map.. I am not able to do.
https://github.com/ro-hit81/hello-world/blob/master/deep.ipynb
Please help me.
